name: 'Deployment'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: 'Deploying'

    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Download Plan Artifact
      uses: actions/download-artifact@v5
      with:
        name: testfile-${{ github.run_number }}
        github-token: ${{ github.token }}
        repository: ${{ github.repository }}
        run-id: 19521989360
        # run-id: ${{ github.event.pull_request.head.sha }}
        # github-token: ${{ secrets.GITHUB_TOKEN }}