name: 'Deployment'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/buildworkflow.yml
    
  deploy:
    name: 'Deploying'
    runs-on: ubuntu-latest
    environment: production
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Download Plan Artifact
      uses: actions/download-artifact@v4
      with:
        name: testfile-${{ needs.build.outputs.run-id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        run-id: ${{ needs.build.outputs.run-id }}