name: 'Validate and Build'

on:
  push:
    branches-ignore: [ 'main' ]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  validate:
    name: 'Validate'
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install OpenTofu
      run: |
        curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
        chmod +x install-opentofu.sh
        ./install-opentofu.sh --install-method standalone --opentofu-version "1.10.7"
        rm install-opentofu.sh
        tofu --version
    - name: Validate format and syntax
      run: |
        echo "::group::'tofu fmt -check'"
        tofu fmt -check -recursive
        echo "::endgroup::"
        
        echo "::group::'tofu init' (validation only, not use backend)"
        tofu init -backend=false
        echo "::endgroup::"
        
        echo "::group::'tofu validate'"
        tofu validate
        echo "::endgroup::"

  build:
    name: 'Create a file'
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: test
    outputs:
      run-id: ${{ github.run_id }}

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Create a file
      run: 'echo "This is a test file from runner_id: ${{ github.run_id }}" > testfile.txt'

    - name: Upload Test File Artifact
      uses: actions/upload-artifact@v4
      with:
        name: testfile-${{ github.event.number }}
        path: testfile.txt
