name: 'Validate'

on:
  push:
    branches-ignore: [ 'main' ]

permissions:
  contents: read

jobs:
  validate:
    name: 'Validate'
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install OpenTofu
      run: |
        curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
        chmod +x install-opentofu.sh
        ./install-opentofu.sh --install-method standalone --opentofu-version "1.10.7"
        rm install-opentofu.sh
        tofu --version
    - name: Validate format and syntax
      run: |
        echo "::group::'tofu fmt -check'"
        tofu fmt -check -recursive
        echo "::endgroup::"
        
        echo "::group::'tofu init' (validation only, not use backend)"
        tofu init -backend=false
        echo "::endgroup::"
        
        echo "::group::'tofu validate'"
        tofu validate
        echo "::endgroup::"
        echo "::endgroup::"
